Repository senthilrch/kube-fledged, pull requests merged in 2022-03, with the labels that each got.

#145 UPDATED CONTRIBUTING. md
  CONTRIBUTING.md
Labels: enhancement, SODACODE2022, SODALOW

#146 added blogs and presentations to README
  README.md
Labels: enhancement, SODACODE2022, SODALOW

#149 Issue #134 Permission issue when purging images from cache on OpenShift
  .github/workflows/build-kube-fledged.yml
  .github/workflows/cron-cleanup-workflow-runs.yml
  .github/workflows/manual-cleanup-workflow-runs.yml
  README.md
  cmd/controller/app/controller.go
  cmd/controller/app/controller_test.go
  cmd/controller/main.go
  deploy/kubefledged-operator/helm-charts/kubefledged/README.md
  deploy/kubefledged-operator/helm-charts/kubefledged/templates/deployment-controller.yaml
  deploy/kubefledged-operator/helm-charts/kubefledged/values.yaml
  docs/helm-parameters.md
  go.mod
  go.sum
  hack/verify-golint.sh
  pkg/images/image_helpers.go
  pkg/images/image_manager.go
  pkg/images/image_manager_test.go
Labels: feature, SODACODE2022, SODAHIGH

#150 Add Shout-outs section to README
  README.md
Labels: enhancement, good first issue, SODACODE2022, SODALOW

#151 Feature: priorityClass support
  README.md
  cmd/controller/app/controller.go
  cmd/controller/app/controller_test.go
  cmd/controller/main.go
  deploy/kubefledged-operator/helm-charts/kubefledged/README.md
  deploy/kubefledged-operator/helm-charts/kubefledged/templates/deployment-controller.yaml
  deploy/kubefledged-operator/helm-charts/kubefledged/templates/deployment-webhook-server.yaml
  deploy/kubefledged-operator/helm-charts/kubefledged/values.yaml
  docs/helm-parameters.md
  go.mod
  go.sum
  pkg/images/image_helpers.go
  pkg/images/image_manager.go
  pkg/images/image_manager_test.go
Labels: feature, SODACODE2022, SODAHIGH

#153 Issue #152 push images when commit is pushed to develop branch
  .github/workflows/caller.yml
Labels: enhancement, SODACODE2022, SODAMED

#155 Issue #154 Don't run pull_request job when PR is accepted
  .github/workflows/caller.yml
Labels: enhancement, SODACODE2022, SODAMED
