Repository senthilrch/kube-fledged, pull requests merged in 2022-04, with the labels that each got.

#160 feat(ImageManager): add --job-retention-policy flag to the controller
  README.md
  cmd/controller/app/controller.go
  cmd/controller/app/controller_test.go
  cmd/controller/main.go
  deploy/kubefledged-operator/helm-charts/kubefledged/README.md
  deploy/kubefledged-operator/helm-charts/kubefledged/templates/deployment-controller.yaml
  deploy/kubefledged-operator/helm-charts/kubefledged/values.yaml
  docs/helm-parameters.md
  pkg/images/image_manager.go
  pkg/images/image_manager_test.go
Labels: feature, SODACODE2022, SODAHIGH

#166 refactor: updated versions in gha workflow
  .github/workflows/caller.yml
Labels: enhancement, SODACODE2022, SODAMED

#169 Updated shout-out section Fixes #162
  README.md
Labels: enhancement, SODACODE2022, SODALOW

#172 feat(e2e): add e2e test suite with installation validation
  .github/workflows/build-kube-fledged.yml
  Makefile
  e2etest/controlplane/controlplane.go
  e2etest/controlplane/deploy.go
  e2etest/install_using_helm_chart_test.go
  e2etest/install_using_operator_test.go
  e2etest/install_using_yaml_test.go
  e2etest/main_test.go
  e2etest/utils/file.go
  e2etest/utils/helm.go
  e2etest/utils/pod.go
  go.mod
  go.sum
  hack/run-unit-tests.sh
  hack/update-codegen.sh
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/typed/kubefledged/v1alpha2/fake/fake_imagecache.go
  pkg/client/clientset/versioned/typed/kubefledged/v1alpha2/kubefledged_client.go
Labels: feature, SODACODE2022, SODAHIGH
